// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ يجب تحديث هذه القيم بقيم مشروعك الحقيقي من Firebase Console
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyA2XlcVmpqeO9CLvzJjtuJi69B9bqJY590",
      authDomain: "tcar-e5dcb.firebaseapp.com",
      databaseURL: "https://tcar-e5dcb-default-rtdb.firebaseio.com",
      projectId: "tcar-e5dcb",
      storageBucket: "tcar-e5dcb.appspot.com",
      messagingSenderId: "332513044277",
      appId: "1:332513044277:web:0e2811cd99e760b6b3ce7c",
      measurementId: "G-D2W2Y04M8F"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQJf3dAEjeH8flATCLB7k__sAbZfWtuyg',
    appId: '1:332513044277:android:d234b2df199015b0b3ce7c',
    messagingSenderId: '123456789',
    projectId: 'tcar-e5dcb',
    storageBucket: 'tcar-e5dcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.admin_dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:macos:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.admin_dashboard',
  );
}